# Puerto del servidor embebido
server.port=8088
spring.application.name=email-service

# Integración con el Discovery Server (Netflix Eureka)
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Parámetros del Servidor de Correo (Ejemplo: Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yohincapie@gmail.com
spring.mail.password=

# Protocolos de seguridad obligatorios
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
